theme: jekyll-theme-hacker
title: Welcome to Michael Smith's homepage!
description: feel free to help me become the best programmer I can be. 

This is a **bold** word with an *italic* word. Just seems like bold gets double stars and italic gets one.


